### Variáveis globais
@baseUrl = http://localhost:8080
@apiKey = {{createAccount.response.body.api_key}}

### Criar uma nova conta
# @name createAccount
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "John Doe 2",
    "email": "john2@doe.com"
}

### Obter dados da conta
GET {{baseUrl}}/accounts
X-API-Key: {{apiKey}}

### Obter dados da conta
GET {{baseUrl}}/accounts/all
X-API-Key: {{apiKey}}
